server:
  port: 8080
spring:
  application:
    name: DongMenu
  datasource:
    url: jdbc:mysql://localhost:3306/dongmenu_db
    username: root
    password: stefano123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect